version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"

    depends_on:
      - application

    environment:
      - TZ=Asia/Seoul

    restart: unless-stopped

    volumes:
      - /nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx:/var/log/nginx # log파일의 위치
      - /etc/letsencrypt:/etc/letsencrypt #letsencrypt폴더 위치

  application:
    container_name: artfolio

    build:
      context: .
      dockerfile: Dockerfile

    expose:
      - 8080

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/artfolio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1111
      TZ: "Asia/Seoul"

    links:
      - redis6379
      - db

    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot

  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: artfolio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111

    expose:
      - 5432

    volumes:
      - ~/Desktop/postgres/5432/data:/var/lib/postgresql/data

  redis6379:
    container_name: redis6379
    hostname: redis6379
    image: redis:latest

    expose:
      - 6379

    volumes:
      - ~/Desktop/redis/6379/data:/var/lib/redis/data