version: '3.7'

services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: artfolio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111

    restart: always

    ports:
      - 5432:5432

    volumes:
      - ~/Desktop/postgres/5432/data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --port 6379
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    volumes:
      - ~/Desktop/redis/6379:/data

  application:
    container_name: artfolio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/artfolio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1111

    depends_on:
      - redis
      - db