spring:
  profiles:
    active: local

  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  sql.init.mode: always

  jpa:
    defer-datasource-initialization: true   # data.sql이 하이버네이트 초기화 이후 실행하도록 설정하는 옵션
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  # redis 설정
  data:
    redis:
      lettuce:
        pool:
          max-active: 5
          max-idle: 5
          min-idle: 2
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 978078249197-cmok2f3od5tnuurgia1eab2elenkv6mt.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          naver:
            client-id: K692PISIR76RNyBp8luR
            client-secret: T3KdSI3DHm
            redirect-uri: http://syu.artfolio.shop/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: e665d02f2f15df465b84e5f07a980dea
            client-secret: vWOakBYa2NiCMRd7Q1MMvykjXxwJBNFU
            client-authentication-method: POST
            redirect-uri: http://syu.artfolio.shop/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

# AWS 설정
cloud:
  aws:
    credentials:
      accessKey: AKIASNXCUWGU5733BG3J
      secretKey: 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
    s3:
      bucket: artfolio-bucket
      bucket-path: https://artfolio-bucket.s3.ap-northeast-2.amazonaws.com/static
    region:
      static: ap-northeast-2
    stack:
      auto: false

# JWT 설정
jwt:
  secretKey: DA321J3I1DUSJ3QJEALJKAjdlk2j31kd2J3KD1weqkqk32l133K2123JH123HSU32j31j3qwe

  access:
    expiration: 3600000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: Authorization-refresh

# GPT 설정
chatgpt:
  api-key:

naver:
  voice:
    client-id: op9vhnz42x
    client-secret: HZ9WbPXxINLfkC43hnyY4BCkkGer56ei35BgKyZz
    api-url: https://naveropenapi.apigw.ntruss.com/tts-premium/v1/tts

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://db:5432/artfolio
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver

  # redis 설정
  data:
    redis:
      lettuce:
        pool:
          max-active: 5
          max-idle: 5
          min-idle: 2
      host: redis6379
      port: 6379

  jpa:
    defer-datasource-initialization: true   # data.sql이 하이버네이트 초기화 이후 실행하도록 설정하는 옵션
    hibernate.ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100