spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/artfolio
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  data.rest:
    base-path: /api
    detection-strategy: annotated

  # 파일 업로드 관련 설정
  servlet:
    multipart:
      enabled: true
      location: \upload
      max-request-size: 30MB
      max-file-size: 10MB

  sql.init.mode: always

# HTTPs 설정
server:
  ssl:
    key-store: classpath:artfolio.p12
    key-store-type: PKCS12
    key-store-password: 123456
    key-alias: artfolio
  port: 8443
  port.http: 8080

security.require-ssl: true