spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/artfolio
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver

  sql.init.mode: always

  jpa:
    defer-datasource-initialization: true   # data.sql이 하이버네이트 초기화 이후 실행하도록 설정하는 옵션
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  # redis 설정
  data:
    redis:
      lettuce:
        pool:
          max-active: 5
          max-idle: 5
          min-idle: 2
      host: localhost
      port: 6379

# S3 설정
cloud:
  aws:
    credentials:
      accessKey: AKIASNXCUWGU5733BG3J
      secretKey: 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
    s3:
      bucket: artfolio-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false