spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/artfolio
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver

  sql.init.mode: always

  jpa:
    defer-datasource-initialization: true   # data.sql이 하이버네이트 초기화 이후 실행하도록 설정하는 옵션
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  # 파일 업로드 관련 설정
  servlet:
    multipart:
      enabled: true                  # 파일 업로드 가능 여부
      location: classpath:assets/    # 파일 임시 저장 경로
      max-request-size: 30MB
      max-file-size: 5MB

  # 타임리프 설정
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

# HTTPs 설정
server:
  ssl:
    key-store: classpath:artfolio.p12
    key-store-type: PKCS12
    key-store-password: 123456
    key-alias: artfolio
  port: 8443
  port.http: 8080

security.require-ssl: true